version: '3'

services:

  swagger-book:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: swaggerbook
    ports:
      - "8182:3200"
    env_file:
      - ../src/.env
    networks:
      - my-network
networks:
  my-network:
    driver: bridge